### ISSUE TITLE
Roadmap BuildExecutable

### ISSUE THREAD

**Issue by dhoegh** [dhoegh/BuildExecutable.jl#1]
I have created this repository because the `build_executable.jl` in base is left alone in broken condition for long periods. The test of the script pressure the CI and hence is untested in base. I have gotten the scripts in working condition locally on both Windows and Ubuntu. Appveyor is setup to run weakly and as of now the test are passing on both 0.4 and master.
The Plan is to:
- [x] Get travis working
- [x] Register `BuildExecutable.jl` at `METADATA.jl`
- [x] Remove `build_executable.jl` from Base

cc @tkelman
This repository are the actions we discussed in: https://github.com/JuliaLang/julia/pull/11101. Could you take a look at Travis, I cannot seem to get Travis working?

**Comment by tkelman** [comment]
Yes, this could use a code owner and its own separate CI.

It looks like you're using the old-style travis, you should update it to use `language: julia`. And it's apparently trying to write into a read-only location under `/usr/lib`

**Comment by dhoegh** [comment]
When I used new style travis failed during `sudo apt-get install patchelf`. Patchelf is needed as dependancy for the test. See: https://travis-ci.org/dhoegh/BuildExecutable.jl/jobs/85335931

**Comment by tkelman** [comment]
You can add the juliadeps ppa. It looks like patchelf isn't available as an ubuntu package before 14.10.

**Comment by dhoegh** [comment]
@tkelman Thanks for the tip I do now have Travis passing the tests on Linux 0.4 but it fails at master and OSX.

**Comment by dhoegh** [comment]
@tkelman do you have any insights in why OSX fails during build_sysimg in #2?

**Comment by tkelman** [comment]
Undefined symbols on osx, not sure where those should be coming from. Nightly is failing to initialize libgit2.

**Comment by dhoegh** [comment]
Should I file an issue in the Julia repo for the `build_sysimg` failure?

**Comment by tkelman** [comment]
Maybe. The code doesn't really have a responsible owner in base right now, so people might be able to offer suggestions but it will most likely be fixed by you.

**Comment by dhoegh** [comment]
Ok, I will try to look into it. I'm not to good at all this build stuff, I am only a mechanical engineer:). Could it be a CI thing, I cannot test it locally as I do not own a Mac.

**Comment by tkelman** [comment]
> I am only a mechanical engineer:)

So am I. I don't own a mac either, may want to put a request for osx help up on the binary compilation issue since that's related and already open.

**Comment by dhoegh** [comment]
Thank you for your help.
